version: "3.5"
services:
  redisA:
    network_mode: host
    image: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redisdataclusterA:/data
      - ./rediscluster/A:/usr/local/etc/redis
  redisB:
    network_mode: host
    image: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redisdataclusterB:/data
      - ./rediscluster/B:/usr/local/etc/redis
  redisC:
    network_mode: host
    image: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redisdataclusterC:/data
      - ./rediscluster/C:/usr/local/etc/redis
  redisD:
    network_mode: host
    image: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redisdataclusterD:/data
      - ./rediscluster/D:/usr/local/etc/redis
  redisE:
    network_mode: host
    image: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redisdataclusterE:/data
      - ./rediscluster/E:/usr/local/etc/redis
  redisF:
    network_mode: host
    image: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redisdataclusterF:/data
      - ./rediscluster/F:/usr/local/etc/redis
volumes:
  redisdataclusterA:
    external: true
  redisdataclusterB:
    external: true
  redisdataclusterC:
    external: true
  redisdataclusterD:
    external: true
  redisdataclusterE:
    external: true
  redisdataclusterF:
    external: true
#
# redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 --cluster-replicas 1
