declare const path: any;
declare const switcher: ({ type, timestamp, to, from, wid, author, isQuoted, isForwarded, isFromHistory, isFromMe, isFromCheckin, seed, wbi, msg, quoteMsg, location, contact, document, image, audio, video }: {
    type: any;
    timestamp: any;
    to: any;
    from: any;
    wid: any;
    author: any;
    isQuoted: any;
    isForwarded: any;
    isFromHistory: any;
    isFromMe: any;
    isFromCheckin: any;
    seed: any;
    wbi: any;
    msg: any;
    quoteMsg: any;
    location: any;
    contact: any;
    document: any;
    image: any;
    audio: any;
    video: any;
}) => Promise<{
    file: any;
    params: {
        type: any;
        timestamp: any;
        to: any;
        author: any;
        from: any;
        wid: any;
        caption: any;
        forwarded: boolean | undefined;
        quoted: any;
        isFromHistory: any;
        isFromMe: any;
        isFromCheckin: any;
        mimetype: any;
        size: any;
        filename?: undefined;
        seconds?: undefined;
        loop?: undefined;
    } | {
        type: any;
        timestamp: any;
        to: any;
        author: any;
        from: any;
        wid: any;
        forwarded: boolean | undefined;
        quoted: any;
        isFromHistory: any;
        isFromMe: any;
        isFromCheckin: any;
        filename: any;
        mimetype: any;
        size: any;
        caption?: undefined;
        seconds?: undefined;
        loop?: undefined;
    } | {
        type: any;
        timestamp: any;
        to: any;
        author: any;
        from: any;
        wid: any;
        forwarded: boolean | undefined;
        quoted: any;
        isFromHistory: any;
        isFromMe: any;
        isFromCheckin: any;
        seconds: any;
        mimetype: any;
        size: any;
        caption?: undefined;
        filename?: undefined;
        loop?: undefined;
    } | {
        type: any;
        timestamp: any;
        to: any;
        author: any;
        from: any;
        wid: any;
        caption: any;
        forwarded: boolean | undefined;
        isFromHistory: any;
        isFromMe: any;
        isFromCheckin: any;
        quoted: any;
        seconds: any;
        loop: boolean;
        mimetype: any;
        size: any;
        filename?: undefined;
    } | undefined;
    jsontosend: {
        type: any;
        author: any;
        timestamp: any;
        to: any;
        from: any;
        msg: any;
        forwarded: boolean | undefined;
        quoted: any;
        isFromHistory: any;
        isFromMe: any;
        isFromCheckin: any;
        wid: any;
        description?: undefined;
        latitude?: undefined;
        longitude?: undefined;
        vcard?: undefined;
    } | {
        type: any;
        author: any;
        timestamp: any;
        to: any;
        from: any;
        forwarded: boolean | undefined;
        quoted: any;
        isFromHistory: any;
        isFromMe: any;
        isFromCheckin: any;
        wid: any;
        description: any;
        latitude: any;
        longitude: any;
        msg?: undefined;
        vcard?: undefined;
    } | {
        type: any;
        author: any;
        timestamp: any;
        to: any;
        from: any;
        forwarded: boolean | undefined;
        isFromHistory: any;
        isFromMe: any;
        isFromCheckin: any;
        quoted: any;
        vcard: any;
        wid: any;
        msg?: undefined;
        description?: undefined;
        latitude?: undefined;
        longitude?: undefined;
    } | {
        type: any;
        timestamp: any;
        from: any;
        isFromHistory: any;
        isFromMe: any;
        isFromCheckin: any;
        to: any;
        author?: undefined;
        msg?: undefined;
        forwarded?: undefined;
        quoted?: undefined;
        wid?: undefined;
        description?: undefined;
        latitude?: undefined;
        longitude?: undefined;
        vcard?: undefined;
    } | {
        type: any;
        author: any;
        timestamp: any;
        to: any;
        from: any;
        isFromHistory: any;
        isFromMe: any;
        isFromCheckin: any;
        wid: any;
        msg?: undefined;
        forwarded?: undefined;
        quoted?: undefined;
        description?: undefined;
        latitude?: undefined;
        longitude?: undefined;
        vcard?: undefined;
    } | undefined;
}>;
