
module.exports = {
  webhookdelete: require('./webhookdelete'),
  webhookget: require('./webhookget'),
  webhookhistory: require('./webhookhistory'),
  webhookpost: require('./webhookpost'),
  webhookput: require('./webhookput'),
  stats: require('./stats'),
  connectionstate: require('./connectionstate'),
  queuerestart: require('./queuerestart'),
  spreadrestart: require('./spreadrestart'),
  signupconnection: require('./signupconnection'),
  connect: require('./connect'),
  contactinfo: require('./contactinfo'),
  disconnect: require('./disconnect'),
  allchats: require('./allchats'),
  alreadytalkedto: require('./alreadytalkedto'),
  startnewchat: require('./startnewchat'),
  sendtextmessage: require('./sendtextmessage'),
  sendlocationmessage: require('./sendlocationmessage'),
  sendcontactmessage: require('./sendcontactmessage'),
  forwardmessage: require('./forwardmessage'),
  loadmessages: require('./loadmessages'),
  senddocumentmessage: require('./senddocumentmessage'),
  sendaudiomessage: require('./sendaudiomessage'),
  sendimagemessage: require('./sendimagemessage'),
  sendmediamessage: require('./sendmediamessage'),
  sendvideomessage: require('./sendvideomessage')
}
