/*

faz aqui, depois leva pro redispack

uid,uuid,NULL,NULL,NULL,NULL,NO,NULL,
tatus,bool,NULL,NULL,NULL,NULL,NO,false,
Nome,varchar,NULL,NULL,NULL,255,YES,NULL,
Fant,varchar,NULL,NULL,NULL,255,YES,NULL,
E,varchar,NULL,NULL,NULL,20,YES,NULL,
EST,varchar,NULL,NULL,NULL,20,YES,NULL,
M,varchar,NULL,NULL,NULL,15,YES,NULL,
NAE,int4,32,NULL,0,NULL,YES,NULL,
RT,int4,32,NULL,0,NULL,YES,NULL,
CNPJ,varchar,NULL,NULL,NULL,14,YES,NULL,
CPF,varchar,NULL,NULL,NULL,11,YES,NULL,
xLgr,varchar,NULL,NULL,NULL,60,YES,NULL,
nro,varchar,NULL,NULL,NULL,60,YES,NULL,
xCpl,varchar,NULL,NULL,NULL,60,YES,NULL,
xBairro,varchar,NULL,NULL,NULL,60,YES,NULL,
cMun,int4,32,NULL,0,NULL,YES,NULL,
xMun,varchar,NULL,NULL,NULL,60,YES,NULL,
UF,varchar,NULL,NULL,NULL,2,YES,NULL,
CEP,int4,32,NULL,0,NULL,YES,NULL,
cPais,int4,32,NULL,0,NULL,YES,1058,
xPais,varchar,NULL,NULL,NULL,60,YES,'BRASIL'::character varying,
fone,varchar,NULL,NULL,NULL,15,YES,NULL,
code,varchar,NULL,NULL,NULL,100,YES,NULL,
created_at,timestamp,NULL,0,NULL,NULL,NO,'-infinity'::timestamp without time zone,
updated_at,timestamp,NULL,0,NULL,NULL,YES,NULL,
key_xml,varchar,NULL,NULL,NULL,100,YES,NULL,
automation,bool,NULL,NULL,NULL,NULL,NO,false,
document,varchar,NULL,NULL,NULL,14,YES,NULL,
CreatedBy,text,NULL,NULL,NULL,NULL,YES,NULL,
UpdatedBy,text,NULL,NULL,NULL,NULL,YES,NULL,
*/
