const mkBlocklistUpdate = require('./mkBlocklistUpdate')
const mkChatNew = require('./mkChatNew')
const mkChatUpdate = require('./mkChatUpdate')
const mkChatsReceived = require('./mkChatsReceived')
const mkChatsUpdate = require('./mkChatsUpdate')
const mkClose = require('./mkClose')
const mkConnecting = require('./mkConnecting')
const mkConnectionPhoneChange = require('./mkConnectionPhoneChange')
const mkConnectionValidated = require('./mkConnectionValidated')
const mkContactsReceived = require('./mkContactsReceived')
const mkContactUpdate = require('./mkContactUpdate')
const mkCredentialsUpdated = require('./mkCredentialsUpdated')
const mkGroupParticipantsUpdate = require('./mkGroupParticipantsUpdate')
const mkGroupUpdate = require('./mkGroupUpdate')
const mkMessageNew = require('./mkMessageNew')
const mkMessageStatusUpdate = require('./mkMessageStatusUpdate')
const mkMessageUpdate = require('./mkMessageUpdate')
const mkOpen = require('./mkOpen')
const mkQr = require('./mkQr')
const mkReceivedPong = require('./mkReceivedPong')
const mkUserPresenceUpdate = require('./mkUserPresenceUpdate')
const mkUserStatusUpdate = require('./mkUserStatusUpdate')
const mkWsClose = require('./mkWsClose')

const appendHalders = ({ conn, seed }) => {
  conn.on('open', mkOpen(seed))
  conn.on('connecting', mkConnecting(seed))
  conn.on('connection-validated', mkConnectionValidated(seed))
  conn.on('close', mkClose(seed))
  conn.on('ws-close', mkWsClose(seed))
  conn.on('credentials-updated', mkCredentialsUpdated(seed))
  conn.on('qr', mkQr(seed))
  conn.on('connection-phone-change', mkConnectionPhoneChange(seed))
  conn.on('user-status-update', mkUserStatusUpdate(seed))
  conn.on('chat-new', mkChatNew(seed))
  conn.on('contacts-received', mkContactsReceived(seed))
  conn.on('chats-received', mkChatsReceived(seed))
  conn.on('chats-update', mkChatsUpdate(seed))
  conn.on('chat-update', mkChatUpdate(seed))
  conn.on('message-status-update', mkMessageStatusUpdate(seed))
  conn.on('message-update', mkMessageUpdate(seed))
  conn.on('group-participants-update', mkGroupParticipantsUpdate(seed))
  conn.on('group-update', mkGroupUpdate(seed))
  conn.on('received-pong', mkReceivedPong(seed))
  conn.on('blocklist-update', mkBlocklistUpdate(seed))
  conn.on('contact-update', mkContactUpdate(seed))
  conn.on('message-new', mkMessageNew(seed))
  conn.on('user-presence-update', mkUserPresenceUpdate(seed))
}

module.exports = appendHalders
